### PR TITLE
Feature/gui buttons

### PR DESCRIPTION
**Pull request by timkouters**
Hi,

Hereby the new pull request.

Kind regards,
Tim

### CODE REVIEW

**Comment by timkouters** [comment]
Hi,

Hereby a small reminder to finish the pull-request.

Kind regards,
Tim

**Comment by murderbeard** [comment]
Hi Tim,

Been looking into this and I was wondering which Denon AVR you're using. In getVolume is see something about the telnet response being something like "MV575,MVMAX 98".

For the MV? requests I added a fail-safe to ignore any results containing MAX as the response would come in two separate messages, one of which should be ignored. On the AVR 2100W I don't think the response came in on one line. Is this different between AVR sets, any idea?

BR,
Ralph

**Comment by timkouters** [comment]
Hi,

I'm using the X4100W AVR. 
I do not know whether it's different between AVRs. 
When I run "MV?" as a command I get the following response "MV44,MVMAX 98".

For adding the functionality, I've used the following document:
https://www.denon.de/uk/downloads/productdownloads?FileName=Steuerungsprotokoll_IP_RS232C_AVR-X1200W_AVR-X2200W_AVR-X3200W_AVR-X4200W.pdf

My assumption would be that they extend their protocol with backwards-compatibility in mind, but I'm not certain.

Kind regards,
Tim

**Comment by murderbeard** [comment]
Hey Tim,

You'd expect it to be backward-compatible as you say. Would it be possible to get a log from the stdout of the app on your set-up?

I added an extra line to log every socket data event as so; in the READ_MODE section of the command loop:
`this.log("Read result for (" + command + "): " + status);`

On init the device does the this.getVolume() bit and I get the following results in the log:
```
2020-02-18 13:41:47 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
2020-02-18 13:41:48 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MV47
2020-02-18 13:41:48 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MVMAX 98
2020-02-18 13:41:48 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 13:41:48 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Commandbuffer empty. Stopping loop.
```

On my set-up the results come in as two separate data events.

Best regards,
Ralph

**Comment by murderbeard** [comment]
And interestingly enough if I use the new capability volume up the order comes in reversed:

```
2020-02-18 14:05:03 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Decreasing Denon device volume
2020-02-18 14:05:03 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending write-close command MVDOWN
2020-02-18 14:05:03 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Getting Denone Device volume status.
2020-02-18 14:05:04 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 14:05:04 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
2020-02-18 14:05:04 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MVMAX 98
2020-02-18 14:05:04 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MV455
2020-02-18 14:05:04 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 14:05:04 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Commandbuffer empty. Stopping loop.
```

Still two separate events though.

**Comment by timkouters** [comment]
> Hey Tim,
> 
> You'd expect it to be backward-compatible as you say. Would it be possible to get a log from the stdout of the app on your set-up?
> 
> I added an extra line to log every socket data event as so; in the READ_MODE section of the command loop:
> `this.log("Read result for (" + command + "): " + status);`
> 
> On init the device does the this.getVolume() bit and I get the following results in the log:
> 
> ```
> 2020-02-18 13:41:47 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
> 2020-02-18 13:41:48 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MV47
> 2020-02-18 13:41:48 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MVMAX 98
> 2020-02-18 13:41:48 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
> 2020-02-18 13:41:48 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Commandbuffer empty. Stopping loop.
> ```
> 
> On my set-up the results come in as two separate data events.
> 
> Best regards,
> Ralph

Hi,

I will do so this evening.

Kind regards,
Tim

**Comment by timkouters** [comment]
Hi,

As promised; the results when adding the debug statement.

`─────────────── Logging stdout & stderr ───────────────
2020-02-18 21:22:04 [log] [DenonApp] Denon App Booted.
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Denon device initialized with IP: 10.0.0.60
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Getting Denon Device Power Status.
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Getting Denone Device mute status.
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command PW?
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (PW?): PWON
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MU?
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MU?): MUOFF
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MV45
2020-02-18 21:22:05 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:06 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Commandbuffer empty. Stopping loop.
2020-02-18 21:22:14 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Volume down
2020-02-18 21:22:14 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending write-close command MVDOWN
2020-02-18 21:22:15 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:15 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
2020-02-18 21:22:15 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MV445
2020-02-18 21:22:15 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MVMAX 98
2020-02-18 21:22:15 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:15 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Commandbuffer empty. Stopping loop.
2020-02-18 21:22:25 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Volume up
2020-02-18 21:22:25 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending write-close command MVUP
2020-02-18 21:22:25 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Volume up
2020-02-18 21:22:25 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:25 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
2020-02-18 21:22:25 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MV45
2020-02-18 21:22:25 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:25 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending write-close command MVUP
2020-02-18 21:22:26 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:26 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
2020-02-18 21:22:26 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MV455
2020-02-18 21:22:26 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MVMAX 98
2020-02-18 21:22:26 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:26 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Commandbuffer empty. Stopping loop.
2020-02-18 21:22:28 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Volume down
2020-02-18 21:22:28 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending write-close command MVDOWN
2020-02-18 21:22:28 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:28 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
2020-02-18 21:22:28 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MV45
2020-02-18 21:22:28 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:28 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Commandbuffer empty. Stopping loop.
2020-02-18 21:22:34 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Volume up
2020-02-18 21:22:34 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending write-close command MVUP
2020-02-18 21:22:34 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:34 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Sending read command MV?
2020-02-18 21:22:34 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Read result for (MV?): MVMAX 98
2020-02-18 21:22:35 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Socket closed
2020-02-18 21:22:35 [log] [ManagerDrivers] [com.moz.denon.driver] [0] Commandbuffer empty. Stopping loop.
`

**Comment by murderbeard** [comment]
Hey Tim,

Thanks for the log. Looks like messages are coming in the same way as my X2100W.

I've merged your stuff into the main branch with some changes to it for the new status polling feature. Would you mind giving that version a spin and see if it's working okay for you?

Kind regards,
Ralph

**Comment by timkouters** [comment]
Hi,

I've installed your new version and I played with it for a while.
All look OK to me.
I do see extensive logging due to the polling / timeout mechanism but I assume that's what your intent was as well.

Kind regards,
Tim

**Comment by murderbeard** [comment]
Tim's pull request has been merged long ago and is part of the app with appropriate credits in the description. Thanks again Tim, closing the pull request.

**Pull request closed without merging**
